### ISSUE TITLE
Issue with static resources 

### ISSUE THREAD

**Issue by crimsonpixel** [yogoo/xFCP#2]
Not sure whether this extra is still supported, however, recently added to one of my sites and definitely improved performance, however, PDF static resources on mobile devices are not delivered.

Getting the following error:

`[2020-01-29 16:50:53] (ERROR @ /***/****/www/core/cache/includes/elements/modplugin/30.include.cache.php : 101) PHP warning: Cannot modify header information - headers already sent by (output started at /***/****/www/core/model/modx/modresponse.class.php:170)
`
The plugin that the error refers to is the xFCP and is caused when linking to a static resource.

The extra is running on MODX v 2.7.2 on MODX Cloud, using PHP 7.3

If I disable the plugin then the error stops.

I have looked at the static resources in question which are PDFs and I've tried checking and unchecking the cacheable option but it doesn't make any difference.

**Comment by yogoo** [comment]
Hi @crimsonpixel, thank you for reporting the error. This plugin is not maintained anymore and since the code wasn't updated for over 7 years now, I would advise **against** using it for anything live.
